### ISSUE TITLE
Enhancement: "Rich" notifications for camera motion & doorbell events

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#28]
Hey @nzapponi Im sure youre tired of this issue but as you can tell I got a bit obsessed. The key to solving it was I [talked to](https://www.reddit.com/r/homebridge/comments/dkdjem/hb_hk_programming_question_camera_snapshots/) the author of the [homebridge-camera-ffmpeg](https://github.com/KhaosT/homebridge-camera-ffmpeg) project who explained that rich notifications dont work when cameras are added as part of a bridge. The solution is to use a different method of adding cameras (see [here](https://github.com/nfarina/homebridge/wiki/Supporting-IP-Camera)). 

Sooo I've got this working in a [branch on my fork](https://github.com/nikonratm/homebridge-simplisafe3/tree/camera-rich-notifications), haven't submitted a PR yet cause wanted to discuss with you first, when you have a sec. Some points / issues:
- Because of the new way of adding cameras old ones have to be deleted and now adding cameras requires an extra step. Basically you add the platform to HB and then add the cameras separately afterwards (you hit **Add Accessory** > **I Don't Have a Code or Cannot Scan** and the cameras show as available to add, you enter the same HB code. The extra step is worth it IMHO, but a consideration.
- I wrote some code to try and "respect" the privacy shutter e.g. if the shutter is closed dont take a snapshot (when you have a Home app open it requests a snapshot ~every 10 seconds). This only applies to the indoor cams. I think its a decent solution.
- ~~This implementation works pretty well with indoor cam but for some friggin reason it doesnt work with the doorbell camera, for motion or doorbell notifications. The snapshot request gets made to the doorbell cam and when I run the ffmpeg cmd manually it generates an image but for some reason it just doesnt show up on my phone notifications. Sigh. Hopefully will be able to figure this one out with time, I know you dont have one to test.~~

This is your project so wanted to consult you first, welcome your thoughts—again, when you have time. Let me know and can see about submitting a PR. Appreciate all your effort 🙏

Screenshot :
![ss_rnotification](https://user-images.githubusercontent.com/4887959/67182554-5b101200-f394-11e9-8793-89ecc8ad3e3f.jpg)

Edit: it is working with doorbell!

**Comment by nikonratm** [comment]
Update: oh shit, works for doorbell too—w00t!

![ss_rnotification_db](https://user-images.githubusercontent.com/4887959/67184011-98c26a00-f397-11e9-85f4-af8c54a25c83.jpg)

**Comment by virtualjad** [comment]
@nikonratm great work...would love to see this implemented, especially the snapshots. It would be great to avoid opening the camera and waiting for video feed when all i'm looking for is a quick glance (especially since camera view drives my pi4's CPU to ~30%+, even with ffmpeg codecs running optimally).

Quick question: does your solution grab video/images from simplisafe cloud, or locally? I ask because I noticed cam views via home/homebridge has significantly *less* latency than the simplisafe app in its current implementation. Would hate for that to change.

**Comment by nikonratm** [comment]
It uses the same video feed as the full camera view just grabs 1 frame. Ideally we’d be able to pull just an image file from somewhere but seems like SS doesn’t generate one. Yea speed of this solution is something I’d like to see about improving.

Happy to help, I’m still just so pissed at SS for backing out on official HomeKit support.

**Comment by nzapponi** [comment]
Woah, this is great, thanks for all the hard work put into this!

I’ll review the proposed changes between today and tomorrow and merge them in. 

QQ @nikonratm: have you tested on how well it supports loss of power to homebridge/restarts/etc?

It’s something that wasn’t too easy to support on the other accessories, and I want to make sure we cover before merging in. 

Let me know, thanks!

**Comment by nikonratm** [comment]
Haven’t really tested power loss etc, what exactly would I need to test? The cameras are still part of homebridge (behind the scenes) even though they show in Homekit as not, so recovery after restarts etc should be pretty much the same. I didn’t modify most of your original camera code.

FYI, I think the snapshots sometimes “fail” because it takes too long to get the stream (and perhaps removing the DNS lookup could speed things up?) but this is working most of the time for me. Perhaps you’ll notice other ways to speed up in your code review (and as you mentioned in other thread, local API would be great but 🤷🏽‍♂️).

Great I’ll submit a PR

Cool, lemme know

**Comment by nzapponi** [comment]
Great thanks! I'll review today!

**Comment by nzapponi** [comment]
@nikonratm I merged your PR into the [door-lock branch](https://github.com/nzapponi/homebridge-simplisafe3/tree/door-lock) for me to test it over the next few days - I'll merge it in by Friday!

Thanks for the help here

**Comment by graanco** [comment]
Simplisafe has thumbnails....var p = On.functionLog("streamThumbnails").enter();
        try {
            var f = r.defer();
            if ("function" != typeof fetch) f.reject();
            else {
                var m = In + "/" + n + "/";
                m += "mjpg?x=" + a, m += "&fr=" + (c || 1), i && (m += "&ts=" + Math.floor(i / 1e3)), o && (m += "&duration=" + Math.floor(o / 1e3)), fetch(m, {
                    method: "GET",
                    headers: {
                        Authorization: "Bearer " + l.authAccessToken
                    }
                }).then(u, d)
            }
            return f.promise



var e = o.apiHost + o.apiPath,
t = e + "/users";
ft = t, mt = t + "/passwordReset";

var n = t + "/{uid}";
gt = n + "/subscriptions",
ht = n + "/paymentMethods",
vt = n + "/chase/paymentMethods",
yt = n + "/addresses";

var r = e + "/utility";
St = e + "/subscriptions/{sid}",
bt = St + "/pinUnlock",
Ct = St + "/events",
wt = St + "/state",
Et = St + "/upgrade",
At = St + "/permitInfo",
Lt = St + "/plan/{sku}",
Pt = St + "/cameras/subscription",
Tt = Pt + "/all",
It = St + "/cameras/swap/{uuidFrom}/{uuidTo}",
xt = St + "/alertsUsers",
Rt = xt + "/{alertsUserId}",
Dt = xt + "/{alertsUserId}/confirm",
kt = xt + "/{alertsUserId}/resend",
Ut = r + "/smsCarriers",
Mt = r + "/zipInfo/{zip}",
Ot = r + "/zones",
Nt = e + "/activation/{uid}",
Ft = Nt + "/check/{serial}",
$t = Nt + "/planOptions",
Bt = Nt + "/activationCode/{code}",
Vt = Nt + "/{sid}/service",
zt = Nt + "/{sid}/location",
jt = e + "/subscriptions/{sid}/copsOptIn",
_t = Nt + "/{sid}/reactivate",
Ht = n + "/loginInfo",
Gt = n + "/emailPreferences",
Wt = n + "/mobileDevices",
qt = n + "/orderHistory",
Xt = n + "/paymentHistory",
Zt = St + "/pins",
Kt = St + "/settings",
Yt = e + "/subscriptions/service/plans",
Jt = e + "/ss3/subscriptions/{sid}",
Qt = Jt + "/settings/{section}",
en = Jt + "/state",
Rn = o.simpliSafeUrl + "/account/{uid}/alarm-certificate/{sid}",
tn = Jt + "/sensors",
nn = Jt + "/testAndName",
rn = Jt + "/messages",
an = rn + "/{id}",
on = St + "/cameras",
sn = on + "/privacy",
ln = e + "/cameras/{uuid}",
cn = ln + "/settings",
/***** here *******/ un = e + "/doorlock/{sid}/{serial}/command";

var a = e + "/api/chase";
dn = a + "/oas/cuid",
pn = a + "/eu/prepare",
fn = n + "/chase/token/{region}";

var i = e + "/integration/nest/{sid}";

mn = i + "/oauthToken",
gn = i + "/structureId",
hn = i + "/info", vn = i;

var s = e + "/integration/alexa/{sid}";
yn = s + "/tokens", Sn = s + "/{tokenId}";

var c = e + "/integration/googlehome/{sid}";
bn = c + "/tokens", Cn = c + "/{tokenId}";

var l = e + "/integration/august/{sid}";
wn = l + "/info",
***** AUGUST ***** En = l + "/lockSettings",
An = l + "/codeExchange", Ln = l + "/token";

var u = o.simpliSafeUrl + "/admin/phone/recording";
Pn = u + "/pause",
Tn = u + "/unpause",
In = o.mediaHost + o.mediaPath,
xn = In + "/{uuid}/mp4",
kn = e + "/tracking",
Un = kn + "/{vid}",
Mn = Un + "/event"

**Comment by nikonratm** [comment]
@graanco Interesting about the thumbnails. One would hope this would be faster than piping a stream through FFmpeg to get the 1 frame but then again that URL is still a stream, its an mjpeg (motion jpeg) stream as opposed to already-saved images and frankly it still seems kinda slow (thats my experience in the app too, the preview jpgs it shows are slow as heck).

Anyway when I try to curl to the URL in that code e.g. https://52.2.241.141/v1/uuid/mjpg?x=480&fr=1 it starts a continuous stream despite the fr=1. Seems like we'd have to code some logic for stopping after one frame unless someone can tell the format for a URL that'll just download 1 jpg and close the stream?

**Comment by nzapponi** [comment]
@nikonratm thanks for the awesome support on this, seriously.
I have now added this to v1.3.0.

**Comment by virtualjad** [comment]
@nikonratm i'm still not getting any rich notifications with the latest update (just the text). I checked my notification settings in Home and settings and all looks good. Can you confirm yours is working with the PR merge into v1.3.0?

**Comment by nzapponi** [comment]
@virtualjad did you remove the camera and add it again using the new method (add it as a separate accessory)?

**Comment by nikonratm** [comment]
Yea it’s working for me in 1.3.x but like @nzapponi said you have to remove old cameras and add them the “new” way. (Obviously this is a one-time thing)

**Comment by nikonratm** [comment]
BTW, you can tell if camera is setup properly (old vs new way) by clicking into the settings for it, if it still shows “Bridge” it’s the old way (and you won’t get rich notifications)

**Comment by nzapponi** [comment]
I added a simple new way of removing the old camera. Follow these @virtualjad :

1. Edit config.json, set `"cameras": false` and `"persistAccessories": false`
2. Restart Homebridge and check that the camera disappears from the Home app
3. Edit config.json again, set `"cameras": true` and remove `persistAccessories`
4. Restart Homebridge and follow the new instructions on the Readme to add the camera(s) - basically you need to go into the Home app and choose + -> Add Accessory -> I Don't Have a Code or Cannot Scan -> select your cameras.

**Comment by beardedbrewguy** [comment]
I'm having issues as well. I removed all the cameras (I had to completely remove home bridge and setup it up again as I could not remove the cameras any other way) and re-added them using the new method. I kept seeing the following FFMPEG errors in the logs:

(node:10106) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ffmpegPath' of null
    at CameraSource.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/simplicam.js:343:41)
    at Accessory._handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:934:25)
    at HAPServer.emit (events.js:210:5)
    at HAPServer._handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:1035:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:210:5)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:10106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)


I fixed this by specifying the location of ffmpeg in config.json as such:

"cameraOptions": {
        "ffmpegPath": "/usr/local/bin/ffmpeg"

I no longer see those errors in the log but I'm not getting motion notifications from the doorbell and the indoor room camera gives me a motion notification but there is no attached snapshot from the camera.

**Comment by virtualjad** [comment]
> @virtualjad did you remove the camera and add it again using the new method (add it as a separate accessory)?

Yup, I realized that was the case when I remembered cameras should be added externally. Only issue is old cameras stuck, even after following the removal steps. I had to kill the accessories cache as well. I'm not getting notifications with a preview...and the Home snapshot updates every 15 secs. So...looking good.

I'm troubleshooting a new issue though - since the update I'm getting about a 20 sec video lag (i.e. unusable). I've switched between 720p and 1080p with no real difference. I also noticed the logs show a 1080p stream even when I set the camera to 720p in the app.

**Comment by virtualjad** [comment]
> I'm troubleshooting a new issue though - since the update I'm getting about a 20 sec video lag (i.e. unusable). I've switched between 720p and 1080p with no real difference. I also noticed the logs show a 1080p stream even when I set the camera to 720p in the app.

Quick update - I rebooted the pi and lag is now down to ~5sec in 720p. In the SimpliSafe app there's about a 2sec lag.

**Comment by graanco** [comment]
Quick and easy way to reload accessories. Shutdown HB delete accessories folder in the ~/.homebridge location... start the HB process. And it should recapture all the accessories.

**Comment by graanco** [comment]
Change this line in the simpicam file

https://${this.serverIpAddress}/v1/${this.cameraConfig.uuid}/flv?x=${request.width}

To 

https://${this.serverIpAddress}/v1/${this.cameraConfig.uuid}/flv

This will pull the stream at the SSAPI settings

**Comment by nikonratm** [comment]
@beardedbrewguy I will submit a fix for that error.

@virtualjad Yea, the lag isnt great but thats really just a factor of hardware (e.g. Pi vs other) + SS cloud which I find to be pretty slow (2s lag in their official app is pretty bad, lets be honest). But streaming shouldn't be any slower this way than previous, that code didn't change. When you say the logs show a 1080p stream even when camera is set to 720—are you sure? Can you paste your [de-identified] log here, for me the stream is determined by camera settings see my comment that includes the relevant log in other thread: https://github.com/nzapponi/homebridge-simplisafe3/issues/35#issuecomment-546125891

Yea, in general would love to brainstorm ways to speed things up = "enhancement"

**Comment by graanco** [comment]
you I am very curious have you tried to capture the traffic from the ip of SS base yet?

**Comment by nzapponi** [comment]
@graanco I don't think you'll get anything interesting out of there since it's all SSL encrypted...

**Comment by nzapponi** [comment]
@virtualjad I found a bug in the `persistAccessories` bit which is what didn't allow you to clear the old camera properly. It should work now

**Comment by nikonratm** [comment]
Closing this again, if people have new issues or thoughts on speed improvement etc please create a new issue so we can avoid megathread.

**Comment by nikonratm** [comment]
Sorry all, my last commit has an error with Babel compilation, I've submitted a PR to fix it.

**Comment by tasansal** [comment]
> Sorry all, my last commit has an error with Babel compilation, I've submitted a PR to fix it.

I was about to start a new issue for this. This is the error I get is below, I think it is because of the namespace error. It seems to delay everything, including alarm/motion notifications. Apart from that works great!

(node:1570) UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'ffmpeg' before initialization
    at CameraSource.handleSnapshotRequest (/homebridge/node_modules/homebridge-simplisafe3/accessories/simplicam.js:343:22)
    at Accessory._handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:934:25)
    at HAPServer.emit (events.js:210:5)) ...

**Comment by nikonratm** [comment]
@tasansal Yea, sorry, thats the error, will be fixed by PR above.
